exclude: (^android/|^build/|^coverage/|^ios/|^linux/|^macos/|^web/|^windows/)
fail_fast: true

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-case-conflict
      - id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-sort-keys"]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: trailing-whitespace
      - id: double-quote-string-fixer

  - repo: local
    hooks:
      - id: dart format
        name: dart format
        language: system
        entry: dart format --set-exit-if-changed
        files: \.dart$

      - id: flutter analyze
        name: flutter analyze
        language: system
        entry: flutter analyze --fatal-infos --fatal-warnings
        files: \.dart$

      - id: flutter test
        name: flutter test
        language: system
        entry: flutter test --coverage
        pass_filenames: false

      - id: test coverage
        name: test coverage
        language: system
        entry: dart run test_cov_console -l
        pass_filenames: false
        verbose: true
