FROM registry.gitlab.com/fdroid/docker-executable-fdroidserver:master

RUN apt-get update && apt-get install -y \
  openjdk-17-jdk-headless \
  && rm -rf /var/lib/apt/lists/* \
  && update-java-alternatives -a
